<?php

/* Screen */
defined('MAX_SCREEN_WIDTH') || define('MAX_SCREEN_WIDTH', 160);
defined('MAX_SCREEN_HEIGHT') || define('MAX_SCREEN_HEIGHT', 40);
defined('DEFAULT_SCREEN_WIDTH') || define('DEFAULT_SCREEN_WIDTH', MAX_SCREEN_WIDTH);
defined('DEFAULT_SCREEN_HEIGHT') || define('DEFAULT_SCREEN_HEIGHT', MAX_SCREEN_HEIGHT);
/* Dialogs */
defined('DEFAULT_DIALOG_WIDTH') || define('DEFAULT_DIALOG_WIDTH', 50);
defined('DEFAULT_DIALOG_HEIGHT') || define('DEFAULT_DIALOG_HEIGHT', 3);
defined('DEFAULT_SELECT_DIALOG_WIDTH') || define('DEFAULT_SELECT_DIALOG_WIDTH', 30);
defined('DEFAULT_DIALOG_X_POSITION') || define('DEFAULT_DIALOG_X_POSITION', 0);
defined('DEFAULT_DIALOG_Y_POSITION') || define('DEFAULT_DIALOG_Y_POSITION', 0);
defined('DEFAULT_FPS') || define('DEFAULT_FPS', 60);
defined('DEFAULT_ASSETS_PATH') || define('DEFAULT_ASSETS_PATH', 'assets');
defined('DEFAULT_LOGS_DIR') || define('DEFAULT_LOGS_DIR', 'logs');
defined('DEFAULT_LOG_LEVEL') || define('DEFAULT_LOG_LEVEL', 'debug');
/* Splash */
defined('DEFAULT_SPLASH_TEXTURE_PATH') || define('DEFAULT_SPLASH_TEXTURE_PATH', DEFAULT_ASSETS_PATH . '/splash.texture');
defined('DEFAULT_SPLASH_SCREEN_DURATION') || define('DEFAULT_SPLASH_SCREEN_DURATION', 3);
/* Windows  */
defined('DEFAULT_WINDOW_WIDTH') || define('DEFAULT_WINDOW_WIDTH', 80);
defined('DEFAULT_WINDOW_HEIGHT') || define('DEFAULT_WINDOW_HEIGHT', 30);
/* Grid */
defined('DEFAULT_GRID_WIDTH') || define('DEFAULT_GRID_WIDTH', 10);
defined('DEFAULT_GRID_HEIGHT') || define('DEFAULT_GRID_HEIGHT', 10);
/* Menu */
defined('DEFAULT_MENU_WIDTH') || define('DEFAULT_MENU_WIDTH', 16);
defined('DEFAULT_MENU_HEIGHT') || define('DEFAULT_MENU_HEIGHT', 3);
